composer:
    build: config/docker/php/composer
    volumes:
        - ./composer.json:/scripts/composer.json:rw
        - ./composer.lock:/scripts/composer.lock:rw
        - ./bin:/scripts/bin:rw
    volumes_from:
        - vendor
vendor:
    build: config/docker/php/vendor
    volumes:
        - ./vendor/:/scripts/vendor/
behat:
    build: config/docker/php/behat
    volumes:
        - ./behat.yml:/scripts/behat.yml/:ro
        - ./src:/scripts/src/:ro
        - ./features:/scripts/features/:rw
    volumes_from:
        - vendor
    links:
        - mysql
        - postgresql
mysql:
    image: mariadb:10.2
    environment:
        MYSQL_DATABASE: db
        MYSQL_USER: user
        MYSQL_PASSWORD: password
        MYSQL_ROOT_PASSWORD: rootpassword
postgresql:
    image: postgres:9.6
    environment:
        POSTGRES_DATABASE: db
        POSTGRES_USER: user
        POSTGRES_PASSWORD: password
        POSTGRES_ROOT_PASSWORD: password
